server:
  port: 8003

node:
  profiles:
    active: dev
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 1000s
    password:
    ssl: false
  datasource:
    url:
    username:
    password: